### ISSUE TITLE
Unknown crash that might be related to this plugin

### ISSUE THREAD

**Issue by PEMapModder** [iksaku/MoreHealth#2]
There is [an unknown crash on the PocketMine crash archive](https://github.com/LegendOfMCPE/HealthBar/blob/master/src/HealthBar/HealthBarCommand.php#L113) that claims to be caused by MoreHealth. Yet, the error message is about @mkdir(), and according to @shoghicp, this is most likely that an unknown error occurred, and the last (possibly hidden) error traces to this one. Anyway, it is in an old version, and I'm not even sure if this plugin is responsible for this (most likely not), but issue submitted just to keep you aware of this possible crash.

**Comment by iksaku** [comment]
Thank you, at this time we don't have any type of crash... Anyways, the current version on this repo doesn't work at 100%, just the YAML provider... But meh

**Comment by iksaku** [comment]
Well fixed xD I will re-work on this :3
